# frozen_string_literal: true

require_relative "lib/dewasm/pozeiden/version"

Gem::Specification.new do |spec|
  spec.name = "dewasm-pozeiden"
  spec.version = Dewasm::Pozeiden::VERSION
  spec.authors = ["Hiroya Fujinami"]
  spec.email = "make.just.on@gmail.com"

  spec.summary = "Mermaid diagram rendering in pure Ruby, from pozeiden compiled to WebAssembly"
  spec.description = "The pozeiden mermaid renderer, compiled to wasm32-wasi and converted to " \
                     "pure Ruby by dewasm. No native extension and no runtime dependency."
  spec.homepage = "https://github.com/dewasm/ruby-pozeiden"
  spec.license = "PolyForm-Noncommercial-1.0.0"
  spec.required_ruby_version = ">= 3.4"

  spec.metadata["source_code_uri"] = spec.homepage

  # The converted module is generated by `rake generate` and not committed,
  # so it is added to the file list explicitly.
  spec.files = `git ls-files -z`.split("\x0").reject { |path| path.start_with?("test/", "wasm/") } +
               ["lib/dewasm/pozeiden/wasm_module.rb"]
  spec.require_paths = ["lib"]
end
