# frozen_string_literal: true

require_relative "lib/dewasm/pozeiden/version"

Gem::Specification.new do |spec|
  spec.name = "dewasm-pozeiden"
  spec.version = Dewasm::Pozeiden::VERSION
  spec.authors = ["Hiroya Fujinami"]
  spec.email = "make.just.on@gmail.com"

  spec.summary = "Mermaid diagram rendering in pure Ruby, from pozeiden compiled to WebAssembly"
  spec.description =
    "The pozeiden mermaid renderer, compiled to wasm32-wasi and converted to " \
      "pure Ruby by dewasm. No native extension and no runtime dependency."
  spec.homepage = "https://github.com/dewasm/ruby-pozeiden"
  spec.licenses = %w[MIT PolyForm-Noncommercial-1.0.0]
  spec.required_ruby_version = ">= 3.4"

  spec.metadata["homepage_uri"] = spec.homepage
  spec.metadata["source_code_uri"] = spec.homepage
  spec.metadata["rubygems_mfa_required"] = "true"

  # lib/dewasm/pozeiden/wasm_module.rb is generated by `rake generate` and not committed, so the list is built from the directory rather than from git.
  spec.files = Dir["lib/**/*.rb"] + %w[LICENSE LICENSE-POZEIDEN README.md]
  spec.require_paths = ["lib"]
end
